# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/uolko/study/gputask/GPGPUTasks2025

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/uolko/study/gputask/GPGPUTasks2025

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/uolko/study/gputask/GPGPUTasks2025/CMakeFiles /home/uolko/study/gputask/GPGPUTasks2025//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/uolko/study/gputask/GPGPUTasks2025/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GPGPUTasks_core

# Build rule for target.
GPGPUTasks_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GPGPUTasks_core
.PHONY : GPGPUTasks_core

# fast build rule for target.
GPGPUTasks_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GPGPUTasks_core.dir/build.make CMakeFiles/GPGPUTasks_core.dir/build
.PHONY : GPGPUTasks_core/fast

#=============================================================================
# Target rules for targets named main_aplusb

# Build rule for target.
main_aplusb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main_aplusb
.PHONY : main_aplusb

# fast build rule for target.
main_aplusb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_aplusb.dir/build.make CMakeFiles/main_aplusb.dir/build
.PHONY : main_aplusb/fast

#=============================================================================
# Target rules for targets named main_aplusb_matrix

# Build rule for target.
main_aplusb_matrix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main_aplusb_matrix
.PHONY : main_aplusb_matrix

# fast build rule for target.
main_aplusb_matrix/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_aplusb_matrix.dir/build.make CMakeFiles/main_aplusb_matrix.dir/build
.PHONY : main_aplusb_matrix/fast

#=============================================================================
# Target rules for targets named libbase

# Build rule for target.
libbase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libbase
.PHONY : libbase

# fast build rule for target.
libbase/fast:
	$(MAKE) $(MAKESILENT) -f libs/base/CMakeFiles/libbase.dir/build.make libs/base/CMakeFiles/libbase.dir/build
.PHONY : libbase/fast

#=============================================================================
# Target rules for targets named libimages

# Build rule for target.
libimages: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libimages
.PHONY : libimages

# fast build rule for target.
libimages/fast:
	$(MAKE) $(MAKESILENT) -f libs/images/CMakeFiles/libimages.dir/build.make libs/images/CMakeFiles/libimages.dir/build
.PHONY : libimages/fast

#=============================================================================
# Target rules for targets named libutils

# Build rule for target.
libutils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libutils
.PHONY : libutils

# fast build rule for target.
libutils/fast:
	$(MAKE) $(MAKESILENT) -f libs/utils/CMakeFiles/libutils.dir/build.make libs/utils/CMakeFiles/libutils.dir/build
.PHONY : libutils/fast

#=============================================================================
# Target rules for targets named libclew

# Build rule for target.
libclew: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libclew
.PHONY : libclew

# fast build rule for target.
libclew/fast:
	$(MAKE) $(MAKESILENT) -f libs/clew/CMakeFiles/libclew.dir/build.make libs/clew/CMakeFiles/libclew.dir/build
.PHONY : libclew/fast

#=============================================================================
# Target rules for targets named hexdumparray

# Build rule for target.
hexdumparray: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hexdumparray
.PHONY : hexdumparray

# fast build rule for target.
hexdumparray/fast:
	$(MAKE) $(MAKESILENT) -f libs/gpu/CMakeFiles/hexdumparray.dir/build.make libs/gpu/CMakeFiles/hexdumparray.dir/build
.PHONY : hexdumparray/fast

#=============================================================================
# Target rules for targets named libgpu

# Build rule for target.
libgpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libgpu
.PHONY : libgpu

# fast build rule for target.
libgpu/fast:
	$(MAKE) $(MAKESILENT) -f libs/gpu/CMakeFiles/libgpu.dir/build.make libs/gpu/CMakeFiles/libgpu.dir/build
.PHONY : libgpu/fast

#=============================================================================
# Target rules for targets named libgpu_test

# Build rule for target.
libgpu_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libgpu_test
.PHONY : libgpu_test

# fast build rule for target.
libgpu_test/fast:
	$(MAKE) $(MAKESILENT) -f libs/gpu/CMakeFiles/libgpu_test.dir/build.make libs/gpu/CMakeFiles/libgpu_test.dir/build
.PHONY : libgpu_test/fast

src/kernels/cu/aplusb.o: src/kernels/cu/aplusb.cu.o
.PHONY : src/kernels/cu/aplusb.o

# target to build an object file
src/kernels/cu/aplusb.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GPGPUTasks_core.dir/build.make CMakeFiles/GPGPUTasks_core.dir/src/kernels/cu/aplusb.cu.o
.PHONY : src/kernels/cu/aplusb.cu.o

src/kernels/cu/aplusb.i: src/kernels/cu/aplusb.cu.i
.PHONY : src/kernels/cu/aplusb.i

# target to preprocess a source file
src/kernels/cu/aplusb.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GPGPUTasks_core.dir/build.make CMakeFiles/GPGPUTasks_core.dir/src/kernels/cu/aplusb.cu.i
.PHONY : src/kernels/cu/aplusb.cu.i

src/kernels/cu/aplusb.s: src/kernels/cu/aplusb.cu.s
.PHONY : src/kernels/cu/aplusb.s

# target to generate assembly for a file
src/kernels/cu/aplusb.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GPGPUTasks_core.dir/build.make CMakeFiles/GPGPUTasks_core.dir/src/kernels/cu/aplusb.cu.s
.PHONY : src/kernels/cu/aplusb.cu.s

src/kernels/cu/aplusb_matrix_bad.o: src/kernels/cu/aplusb_matrix_bad.cu.o
.PHONY : src/kernels/cu/aplusb_matrix_bad.o

# target to build an object file
src/kernels/cu/aplusb_matrix_bad.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GPGPUTasks_core.dir/build.make CMakeFiles/GPGPUTasks_core.dir/src/kernels/cu/aplusb_matrix_bad.cu.o
.PHONY : src/kernels/cu/aplusb_matrix_bad.cu.o

src/kernels/cu/aplusb_matrix_bad.i: src/kernels/cu/aplusb_matrix_bad.cu.i
.PHONY : src/kernels/cu/aplusb_matrix_bad.i

# target to preprocess a source file
src/kernels/cu/aplusb_matrix_bad.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GPGPUTasks_core.dir/build.make CMakeFiles/GPGPUTasks_core.dir/src/kernels/cu/aplusb_matrix_bad.cu.i
.PHONY : src/kernels/cu/aplusb_matrix_bad.cu.i

src/kernels/cu/aplusb_matrix_bad.s: src/kernels/cu/aplusb_matrix_bad.cu.s
.PHONY : src/kernels/cu/aplusb_matrix_bad.s

# target to generate assembly for a file
src/kernels/cu/aplusb_matrix_bad.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GPGPUTasks_core.dir/build.make CMakeFiles/GPGPUTasks_core.dir/src/kernels/cu/aplusb_matrix_bad.cu.s
.PHONY : src/kernels/cu/aplusb_matrix_bad.cu.s

src/kernels/cu/aplusb_matrix_good.o: src/kernels/cu/aplusb_matrix_good.cu.o
.PHONY : src/kernels/cu/aplusb_matrix_good.o

# target to build an object file
src/kernels/cu/aplusb_matrix_good.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GPGPUTasks_core.dir/build.make CMakeFiles/GPGPUTasks_core.dir/src/kernels/cu/aplusb_matrix_good.cu.o
.PHONY : src/kernels/cu/aplusb_matrix_good.cu.o

src/kernels/cu/aplusb_matrix_good.i: src/kernels/cu/aplusb_matrix_good.cu.i
.PHONY : src/kernels/cu/aplusb_matrix_good.i

# target to preprocess a source file
src/kernels/cu/aplusb_matrix_good.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GPGPUTasks_core.dir/build.make CMakeFiles/GPGPUTasks_core.dir/src/kernels/cu/aplusb_matrix_good.cu.i
.PHONY : src/kernels/cu/aplusb_matrix_good.cu.i

src/kernels/cu/aplusb_matrix_good.s: src/kernels/cu/aplusb_matrix_good.cu.s
.PHONY : src/kernels/cu/aplusb_matrix_good.s

# target to generate assembly for a file
src/kernels/cu/aplusb_matrix_good.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GPGPUTasks_core.dir/build.make CMakeFiles/GPGPUTasks_core.dir/src/kernels/cu/aplusb_matrix_good.cu.s
.PHONY : src/kernels/cu/aplusb_matrix_good.cu.s

src/kernels/kernels.o: src/kernels/kernels.cpp.o
.PHONY : src/kernels/kernels.o

# target to build an object file
src/kernels/kernels.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GPGPUTasks_core.dir/build.make CMakeFiles/GPGPUTasks_core.dir/src/kernels/kernels.cpp.o
.PHONY : src/kernels/kernels.cpp.o

src/kernels/kernels.i: src/kernels/kernels.cpp.i
.PHONY : src/kernels/kernels.i

# target to preprocess a source file
src/kernels/kernels.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GPGPUTasks_core.dir/build.make CMakeFiles/GPGPUTasks_core.dir/src/kernels/kernels.cpp.i
.PHONY : src/kernels/kernels.cpp.i

src/kernels/kernels.s: src/kernels/kernels.cpp.s
.PHONY : src/kernels/kernels.s

# target to generate assembly for a file
src/kernels/kernels.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GPGPUTasks_core.dir/build.make CMakeFiles/GPGPUTasks_core.dir/src/kernels/kernels.cpp.s
.PHONY : src/kernels/kernels.cpp.s

src/main_aplusb.o: src/main_aplusb.cpp.o
.PHONY : src/main_aplusb.o

# target to build an object file
src/main_aplusb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_aplusb.dir/build.make CMakeFiles/main_aplusb.dir/src/main_aplusb.cpp.o
.PHONY : src/main_aplusb.cpp.o

src/main_aplusb.i: src/main_aplusb.cpp.i
.PHONY : src/main_aplusb.i

# target to preprocess a source file
src/main_aplusb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_aplusb.dir/build.make CMakeFiles/main_aplusb.dir/src/main_aplusb.cpp.i
.PHONY : src/main_aplusb.cpp.i

src/main_aplusb.s: src/main_aplusb.cpp.s
.PHONY : src/main_aplusb.s

# target to generate assembly for a file
src/main_aplusb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_aplusb.dir/build.make CMakeFiles/main_aplusb.dir/src/main_aplusb.cpp.s
.PHONY : src/main_aplusb.cpp.s

src/main_aplusb_matrix.o: src/main_aplusb_matrix.cpp.o
.PHONY : src/main_aplusb_matrix.o

# target to build an object file
src/main_aplusb_matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_aplusb_matrix.dir/build.make CMakeFiles/main_aplusb_matrix.dir/src/main_aplusb_matrix.cpp.o
.PHONY : src/main_aplusb_matrix.cpp.o

src/main_aplusb_matrix.i: src/main_aplusb_matrix.cpp.i
.PHONY : src/main_aplusb_matrix.i

# target to preprocess a source file
src/main_aplusb_matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_aplusb_matrix.dir/build.make CMakeFiles/main_aplusb_matrix.dir/src/main_aplusb_matrix.cpp.i
.PHONY : src/main_aplusb_matrix.cpp.i

src/main_aplusb_matrix.s: src/main_aplusb_matrix.cpp.s
.PHONY : src/main_aplusb_matrix.s

# target to generate assembly for a file
src/main_aplusb_matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_aplusb_matrix.dir/build.make CMakeFiles/main_aplusb_matrix.dir/src/main_aplusb_matrix.cpp.s
.PHONY : src/main_aplusb_matrix.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GPGPUTasks_core"
	@echo "... hexdumparray"
	@echo "... libbase"
	@echo "... libclew"
	@echo "... libgpu"
	@echo "... libgpu_test"
	@echo "... libimages"
	@echo "... libutils"
	@echo "... main_aplusb"
	@echo "... main_aplusb_matrix"
	@echo "... src/kernels/cu/aplusb.o"
	@echo "... src/kernels/cu/aplusb.i"
	@echo "... src/kernels/cu/aplusb.s"
	@echo "... src/kernels/cu/aplusb_matrix_bad.o"
	@echo "... src/kernels/cu/aplusb_matrix_bad.i"
	@echo "... src/kernels/cu/aplusb_matrix_bad.s"
	@echo "... src/kernels/cu/aplusb_matrix_good.o"
	@echo "... src/kernels/cu/aplusb_matrix_good.i"
	@echo "... src/kernels/cu/aplusb_matrix_good.s"
	@echo "... src/kernels/kernels.o"
	@echo "... src/kernels/kernels.i"
	@echo "... src/kernels/kernels.s"
	@echo "... src/main_aplusb.o"
	@echo "... src/main_aplusb.i"
	@echo "... src/main_aplusb.s"
	@echo "... src/main_aplusb_matrix.o"
	@echo "... src/main_aplusb_matrix.i"
	@echo "... src/main_aplusb_matrix.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

